### ISSUE TITLE
Choosing multple option at a time.

### ISSUE THREAD

**Issue by bablu-joshi** [Kjuly/KYCircleMenu#12]
i can choose more than 1 option at a time ,which must not be there.(monkey testing)

Kindly give me a solution (only last selection ,or single selection)

**Comment by Kjuly** [comment]
Sorry, I'm not very clear about your question.. Do you mean there's a bug when you select a item (if so, please offer the environment, I'll try to reproduce & fix it)? Or you want the feature of multiple selection feature?

**Comment by bablu-joshi** [comment]
yes ,there is a bug !!..i dont want multiple selection .!! Scenario:When i choose 2 button simultaneously (very quickly) then i get pushed to two view on after the other in the navigation stack

**Comment by Kjuly** [comment]
Okay, I see, I'll try to fix it. Thank you! :)

**Comment by Kjuly** [comment]
Um.. how fast you did your do the job? I cannot reproduce it. I even tried to press two buttons at the same time, it only pushed one. And back to root view controller is okay. Everything works fine for me. :)

B.t.w., what's your target iOS version?

**Comment by bablu-joshi** [comment]
I did it on device,ipad increasing radius of menu items ,ios 6.1

**Comment by Kjuly** [comment]
Sorry, this lib is not universal yet, I made it only for iPhone & iPod as the target devices. I'll consider it in the feature. What I can suggest to you for your case is to set the item buttons disabled while pushing the view after one of them is pressed. :)

**Comment by Kjuly** [comment]
Actually, all items should not be touchable while pushing the view controller, cause the UI is blocked by the animation. Have you changed the source code except for the radius?

**Comment by bablu-joshi** [comment]
i have tried disabling user interaction of button ,but i have to go back again when i press back button(do i need to enable it again) ?? how to handle that , i tried using "locks" also for the button action .

**Comment by Kjuly** [comment]
Hi @bablu-joshi , as I said, it should be locked atomically by the UIView animation. Can u show you main code snippet for pushing & popping view controllers? I've no idea about your issue exactly without any code. Thanks :)
