### ISSUE TITLE
I click on one of the sub-button can not be pushed to the following two views Why?

### ISSUE THREAD

**Issue by Ianbao** [Kjuly/KYCircleMenu#13]
I click on one of the sub-button can not be pushed to the following two views Why?

**Comment by Kjuly** [comment]
Do u mean the sample code? Or ur own code? If it's ur own code, can u show me a sample? Or at least describe ur question clearly. Thanks :)

**Comment by Ianbao** [comment]
I put 'KYCircleMenu' plus in my 'TabBarController' projects in the sub-button is not pushed to the next view, it did not change the code.
However, this method is not pushed to go to the next controller

```
completion:^(BOOL finished) {
    [self.navigationController pushViewController:viewController animated:YES];
}
```

And I suspect that will not 'Tabbar' a relationship

**Comment by Kjuly** [comment]
Plz check whether your `self.navigationController` is nil. :)
