### ISSUE TITLE
Customisation with Storyboard

### ISSUE THREAD

**Issue by ingouackaz** [Kjuly/KYCircleMenu#14]
hi @Kjuly  !

I'm trying to using your library for a personal application in Swift and i would like to know, how can i use  KYCircleMenu with Storyboard for more customization.

I'm trying to work only with the subview of KYCircleMenu but it does not work .... . 

Any idea ?

**Comment by Kjuly** [comment]
I'd sorry to say that it doesn't support Storyboard (and i'm not familiar with the Storyboard) for customisation jobs. You can take a look at the demo code, it's not hart to use it programmatically. :)

**Comment by Kjuly** [comment]
B.t.w., maybe u'd like this issue https://github.com/Kjuly/KYCircleMenu/issues/7#issuecomment-15622696, it mentioned Storyboard related questions. ;)
