### ISSUE TITLE
For menu items 7 to 8

### ISSUE THREAD

**Issue by shoaibhassanWhizpool** [Kjuly/KYCircleMenu#16]
Hi every one,
please tell me how to implement this control for 7 to 8 items so that i can use it into my app
Thanks in advance.

**Comment by Kjuly** [comment]
@shoaibhassanWhizpool sorry, it only supports 6 items at most.

You can try to implement it by urself in [`-_updateButtonsLayoutWithTriangleHypotenuse`][1] method of KYCircleMenu.m.

[1]: https://github.com/Kjuly/KYCircleMenu/blob/dev/KYCircleMenu/KYCircleMenu.m#L339
