### ISSUE TITLE
Problem on iOS7

### ISSUE THREAD

**Issue by geelenstef** [Kjuly/KYCircleMenu#9]
Hello,

When I test the KYCirleMenu on IOS7. I get a white screen.
Any idea where the problem is situated?

**Comment by Kjuly** [comment]
Hey @steaphann , I'll try to test it & fix it when I'm free, thx!

**Comment by Kjuly** [comment]
@steaphann the bug is fixed, thx! :)

**Comment by geelenstef** [comment]
What was the problem ?

**Comment by Kjuly** [comment]
@steaphann seems navigation controller on iOS7 doesn't allow to set a uninitialised view controller to the root view controller.
